apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "core-resource-limits" 
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "500m"
        memory: "1Gi" 
      min:
        cpu: "25m" 
        memory: "128Mi" 
    - type: "Container"
      max:
        cpu: "500m" 
        memory: "1Gi" 
      min:
        cpu: "25m" 
        memory: "128Mi" 
      default:
        cpu: "100m" 
        memory: "128Mi" 
      defaultRequest:
        cpu: "100m" 
        memory: "128Mi" 
      maxLimitRequestRatio:
        cpu: 4
