kind: LimitRange
apiVersion: v1
metadata:
  name: core-resource-limits
spec:
  limits:
    - type: Pod
      max:
        memory: 1Gi
      min:
        memory: 128Mi
    - type: Container
      max:
        memory: 1Gi
      min:
        memory: 128Mi
      default:
        memory: 128Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
